# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']
include: ['_redirects']

# Site Settings
title: "iOS Conf SG 2020"
email: "subh@iosconf.sg"
description: "The largest iOS developer conference in Southeast Asia."
baseurl: ""
url: "https://2020.iosconf.sg"
permalink: "/blog/:title"

# Organizer Info
organizerName: "CU Society and iOS Dev Scout"
organizerAlternateName: "CU Society & iOS Dev Scout"
organizerDescription: "CU Society & iOS Dev Scout"
organizerEmail: "subh@iosconf.sg"
organizerLogo: ""
organizerLink: "https://cu.sg/"

# Head
metaKeywords: "event, iosconfsg, iosconference, apple, programming, ios, watchos, macos, swift"
twitterAccount: "@iOSConfSG"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4sponsorsUrl: "/assets/iOSConfSG-2019-Sponsor-Pack.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/#sponsors", text: "Sponsors"}
 - {permalink: "/#venue", text: "Venue"}
 - {permalink: "/workshop", text: "Workshop"}
 - {permalink: "/team/", text: "Team"}

rightNavigationButtons:
 - {permalink: "/#tickets", text: "Buy tickets"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "iOS Conf <typeout> 2020"
eventDate: "15th to 18th January, 2020"
typeoutTextValues: '"", "SG", "Singapore"'
typeoutFallback: "SG"
heroButtons:
 - {link: "https://ti.to/iosconfsg/2020", text: "Buy Tickets"}

# About Block
aboutTitle: "About iOS Conf SG"
aboutBlock:
 - {title: "Conference", image: "conference.png", text: "2 full days - single-track - conference featuring 20+ pure iOS and Swift programming talks." }
 - {title: "Workshops", image: "workshop.png", text: "2 full days workshop and hands-on experience on SwiftUI, Concurrency and Server-Side Swift."}

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "300", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "4", specialCharacter: "", info: "days", detail: "of pure iOS and Swift talks"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from 10 countries"}
 - {count: "1", specialCharacter: "", info: "track", detail: "plus unlimited coffee"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 5
rockstarSpeakersTitle: "Speakers"
rockstarSpeakersButtonText: "READ More"

# Location Block
# locationBlockTitle: "Conference Venue on 18th and 19th"
# eventLocationName: "Matrix at Biopolis"
# eventLocationLink: "http://www.jtc.gov.sg/industrial-land-and-space/pages/biopolis.aspx"
# eventStreetAddress: "30 Biopolis Street, Singapore 138671"
# eventAddressLocalityRegion: "Singapore"
# eventPostalCode: "138671"
# eventAddressCountry: "Singapore"
# eventPlaceCoordinates: "1.304120, 103.791770"
# mapCenterCoordinates: "1.304120, 103.791770"
# mapMobileCenterCoordinates: "1.304120, 103.791770"

# Venue Block
# venueBlockTitle: "Venue"
# venueBigImage: "venue_0.jpg"
# venueSmallImage1: "venue_1.jpg"
# venueSmallImage2: "venue_2.jpg"
# venueTitle: "Matrix at Biopolis"
# venueFeatures: ["30 Biopolis Street", "Singapore - 138671", "Near Buona Vista MRT"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "iOSConfSG"

# Partners Block
organizersTitle: "Sponsors"
partnersC4sponsorsButton: "Become a sponsor"

# Footer
socialLinks:
 - {link: "https://twitter.com/iosconfsg", icon: "twitter"}
 - {link: "https://www.facebook.com/iosconfsg/", icon: "facebook"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.meetup.com/Singapore-iOS-Dev-Scout-Meetup/", text: "iOS Dev Scout"}
   - {link: "https://cu.sg", text: "CU Society"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:subh@iosconf.sg", text: "subh@iosconf.sg"}
 -
  title: "FAQ"
  links:
   - {permalink: "/faq/", text: "Frequently Asked Questions"}
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "We are a bunch of nerds, crazy ones. We love iOS and passionate about building apps in Swift. We are inspired and motivated by the technology and eco-system Apple provides for developers and believe if we bring the power of these technologies to every iOS developers we know then we all can contribute in building smarter and better apps. We started iOS Conf SG in 2015. Since then the community has grown to make the conference the largest iOS developer conference in South East Asia."
coOrganizers: "iOS Conf SG is brought to you by iOS Dev Scout, under the auspices of CU Society. iOS Dev Scout is the iOS developer meetup group that organizes iOS meetups in Singapore every month. CU Society is a non-profit organization that supports various computer technology events and communities in Singapore."

# Workshop
workshopTitle: "Workshop"
enableWorkshop: true

# Workshop About Block
aboutWorkshopTitle: "Workshop Topics"
workshopRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

